name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Apply patches
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "CI"
          ./patches/apply.sh

      - name: Run test
        run: go test -v .
